# Generated by Django 4.2 on 2026-02-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgeos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costevent',
            name='cost_amount',
            field=models.FloatField(default=0),
        ),
    ]
