# Generated by Django 4.2 on 2026-02-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgeos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('schema_json', models.JSONField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('org_id', 'name', 'version')},
            },
        ),
    ]
