# Generated by Django 4.2 on 2026-02-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgeos', '0002_costevent_cost_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(max_length=100)),
                ('module_name', models.CharField(max_length=200)),
                ('attempts', models.IntegerField()),
                ('total_tokens', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
