# Generated by Django 4.2 on 2026-02-28 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forgeos', '0003_generationrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('monthly_token_quota', models.IntegerField(default=10000)),
                ('current_month_tokens', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='generationrecord',
            name='org_id',
        ),
        migrations.AlterField(
            model_name='generationrecord',
            name='module_name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('generation', 'Generation'), ('repair', 'Repair'), ('execution', 'Execution')], max_length=50)),
                ('tokens_used', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_usages', to='forgeos.organization')),
            ],
        ),
        migrations.AddField(
            model_name='generationrecord',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='forgeos.organization'),
        ),
    ]
