# Generated by Django 4.2 on 2026-02-28 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forgeos', '0004_organization_remove_generationrecord_org_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationrecord',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='forgeos.organization'),
        ),
    ]
