# Generated by Django 4.2 on 2026-02-28 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forgeos', '0005_alter_generationrecord_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costevent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='generationrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tokenusage',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='costevent',
            name='org_id',
        ),
        migrations.AddField(
            model_name='costevent',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_events', to='forgeos.organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
