# Generated by Django 4.2 on 2026-02-28 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forgeos', '0006_alter_costevent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costevent',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_events', to='forgeos.organization'),
        ),
    ]
